# -*- restclient -*-
#
# CMPT 315 - Assignment 2
# Author - Chris Mattinson
#
# This file tests the successful and unsuccessful requests
# to the Presentation Feedback System API

# Gets the list of presenters (default path, output in JSON)
GET http://localhost:8080/api/v1/presenters
Authorization: Bearer test

# Gets the list of presenters in XML
GET http://localhost:8080/api/v1/presenters.xml
Authorization: Bearer test

# Gets the list of presenters in JSON
GET http://localhost:8080/api/v1/presenters.json
Authorization: Bearer test

# Attempt to get the list of presenters as unauthorized user
GET http://localhost:8080/api/v1/presenters
Authorization: Bearer notAuthorized

# Attempt to get list of presenters with no authentication header
GET http://localhost:8080/api/v1/presenters

# Gets presentation info for a presenter (Survey form, JSON default)
GET http://localhost:8080/api/v1/presenters/1
Authorization: Bearer test

# Gets presentation info in JSON
GET http://localhost:8080/api/v1/presenters/2.json
Authorization: Bearer test

# Gets presentation info in XML
GET http://localhost:8080/api/v1/presenters/3.xml
Authorization: Bearer test

# Get a single response
GET http://localhost:8080/api/v1/responses/1/mc1
Authorization: Bearer test

# Get the list of responses to the presenter (default JSON)
GET http://localhost:8080/api/v1/responses/1
Authorization: Bearer test

# Get the list of responses to the presenter
GET http://localhost:8080/api/v1/responses/1.json
Authorization: Bearer test

# Get the list of responses to the presenter
GET http://localhost:8080/api/v1/responses/1.xml
Authorization: Bearer test

# Get a single multiple choice response
GET http://localhost:8080/api/v1/responses/1/mc1
Authorization: Bearer test

# Get a single open response
GET http://localhost:8080/api/v1/responses/1/open1
Authorization: Bearer test

# Delete the response for Multiple Choice 1
DELETE http://localhost:8080/api/v1/responses/1
Authorization: Bearer test
Content-Type: application/json

{
	"type": "M/C",
	"number": 1
}

# Attempt to delete a response that doesn't exist
DELETE http://localhost:8080/api/v1/responses/1
Authorization: Bearer test
Content-Type: application/json

{
	"type": "Open",
	"number": 5
}

# Attempt to delete a response with no content
DELETE http://localhost:8080/api/v1/responses/1
Authorization: Bearer test


	