# -*- restclient -*-
#
# Posts an identifier to the API
POST http://localhost:8080/api/v1
Authorization: Bearer jqYPeRSj

# Post an unauthorized user to the API
POST http://localhost:8080/api/v1
Authorization: Bearer notAuthorized

# Gets the list of presenters, shows response and headers underneath
GET http://localhost:8080/api/v1/presenters
Authorization: Bearer jqYPeRSj

# Attempts to get list of presenters as unauthorized student
GET http://localhost:8080/api/v1/presenters
Authorization: Bearer notAuthorized

# Gets presentation info for a presenter
GET http://localhost:8080/api/v1/presenters/cmTYdFRm
Authorization: Bearer jqYPeRSj

# Attempts to get presenter info as unauthorized user
GET http://localhost:8080/api/v1/presenters/cmTYdFRm
Authorization: Bearer notAuthorized

# Sends a response to a question for the authenticated user
POST http://localhost:8080/api/v1/presenters/cmTYdFRm
Authorization: Bearer jqYPeRSj
Content-Type: application/json

{
	"type": "M/C",
	"number": 1,
	"answer": "Neutral"
}

# Send another response to a question as authenticated user
POST http://localhost:8080/api/v1/presenters/cmTYdFRm
Authorization: Bearer jqYPeRSj
Content-Type: application/json

{
	"type": "M/C",
	"number": 2,
	"answer": "Strongly Disagree"
}

# Send another response to a question as authenticated user
POST http://localhost:8080/api/v1/presenters/cmTYdFRm
Authorization: Bearer jqYPeRSj
Content-Type: application/json

{
	"type": "M/C",
	"number": 3,
	"answer": "Strongly Disagree"
}

# Send an Open question response
POST http://localhost:8080/api/v1/presenters/cmTYdFRm
Authorization: Bearer jqYPeRSj
Content-Type: application/json

{
	"type": "Open",
	"number": 1,
	"answer": "Presentation was interesting"
}

# Get the list of responses to the presenter
GET http://localhost:8080/api/v1/responses/cmTYdFRm
Authorization: Bearer jqYPeRSj

# Attempt to get responses for unauthorized user
GET http://localhost:8080/api/v1/responses/cmTYdFRm
Authorization: Bearer notAuthorized
	