# -*- restclient -*-
#
# Posts an identifier to the API
POST http://localhost:8080/api/v1
Content-Type: application/json

{
	"id": "jqYPeRSj"
}
#
# Post an unauthorized user to the API
POST http://localhost:8080/api/v1
Content-Type: application/json

{
	"id": "notAuthorized"
}
# Gets the list of presenters, shows response and headers underneath
GET http://localhost:8080/api/v1/presenters
#
# Gets presentation info for a presenter
GET http://localhost:8080/api/v1/presenters/cmTYdFRm
#
#
POST http://localhost:8080/api/v1/presenters/cmTYdFRm
Content-Type: application/json

{
	"type": "M/C",
	"number": 1,
	"answer": "Agree"
}
	